collections_dir: my_collections
collections:
  publications:
    output: true
    permalink: /:name
    sort_by: date
  musics:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      type: ""
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
